#ifndef LEDMRX_CONFIG_H
#define LEDMRX_CONFIG_H

#define LEDMRX_R0_PIN		GPIOA,0
#define LEDMRX_R1_PIN		GPIOA,1
#define LEDMRX_R2_PIN		GPIOA,2
#define LEDMRX_R3_PIN		GPIOA,3
#define LEDMRX_R4_PIN		GPIOA,4
#define LEDMRX_R5_PIN		GPIOA,5
#define LEDMRX_R6_PIN		GPIOA,6
#define LEDMRX_R7_PIN		GPIOA,7

#define LEDMRX_C0_PIN		GPIOB,0
#define LEDMRX_C1_PIN		GPIOB,1
#define LEDMRX_C2_PIN		GPIOB,5
#define LEDMRX_C3_PIN		GPIOB,6
#define LEDMRX_C4_PIN		GPIOB,7
#define LEDMRX_C5_PIN		GPIOB,8
#define LEDMRX_C6_PIN		GPIOB,9
#define LEDMRX_C7_PIN		GPIOB,10

#endif
